---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 30m
  dependsOn:
    - name: loki
  driftDetection:
    mode: "warn"
  chart:
    spec:
      chart: promtail
      version: "6.*"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h
  values:
    config:
      clients:
        - url: http://loki:3100/loki/api/v1/push
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 128Mi
