---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  driftDetection:
    mode: "warn"
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "82.15.1"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      interval: 12h
  values:
    crds:
      enabled: true
    prometheus:
      prometheusSpec:
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            memory: 1Gi
        retention: 24h
        storageSpec: {}
    grafana:
      enabled: true
      adminPassword: admin
    alertmanager:
      enabled: true
      alertmanagerSpec:
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            memory: 256Mi
    nodeExporter:
      enabled: true
    kubeStateMetrics:
      enabled: true
    kubeEtcd:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
