apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-dep
  name: test-dep
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-dep
  template:
    metadata:
      labels:
        app: test-dep
    spec:
      containers:
        - image: nginx:1.29-alpine
          name: nginx
